### ISSUE TITLE
Kanban Setup  

### ISSUE THREAD

**Issue by shadabwahidullah** [zainsadaqat/spacex-adventures#25]
## Kanban Setup

We have created a project for our GitHub repository. and copied all the tasks to it:
[link to our project](https://github.com/zainsadaqat/spacex-adventures/projects/2)
we are two people in this project.

**Comment by fernandorpm** [comment]
# :warning: Changes Required on this Pull Request! :warning:
Hello there!

You have done a great job so far, and are one step closer to becoming the best developer ever! :sunglasses:

<img src="https://i.imgur.com/FBp5cYj.gif" width="300px" />

- You have done a wonderful job on this project! To highlight:
  - you have demonstrated great skills in following the template :heavy_check_mark: 
  - you have paid attention to almost all of the details :heavy_check_mark: 

## Required
> These changes HAVE TO be completed in order for your project to be approved. This means that the project doesn't attend to Microverse's Standard yet. I know that it can be frustrating, but they should be seen as part of your path to become an even better Developer!

- All of the cards must have someone assigned to them. The reason for this is for us reviewers to validate the workload to guarantee that it's fair for all of the group members.

![image](https://user-images.githubusercontent.com/47700024/141831146-5105e22b-318d-4570-8dcd-f966b4025803.png)

> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Just keep in mind that Microverse has a standard for the project requirements, to guarantee that you will be able to become a great developer, and both you and I have to follow them!

___
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

Cheers and Happy Coding! :heart:

> *As described in the [Code reviews limit Policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of code reviews per project (you can check the exact number in your Dashboard). If you think that the code review was not fair, you can [request a second opinion using this form](https://airtable.com/shrQAqnBwek5a0O0s).*

**Comment by zainsadaqat** [comment]
## Assigned all cards to ourselves.

![](https://media4.giphy.com/media/26u4lOMA8JKSnL9Uk/giphy.gif)

**Comment by fernandorpm** [comment]
# :heavy_check_mark: Pull Request Approved! :heavy_check_mark:
WOW WHAT IS THIS PERFECTION??????? WERE HUMANS SUPPOSED TO BEHOLD SUCH POWER????

Congratulations on your hard work! Please remember to merge the project and don't forget that you're awesome! :heart:

<img src="https://i.imgur.com/gOjmIlL.gif" width="300px" />

- You have done a wonderful job on this project! To highlight:
  - you have demonstrated great skills in following the template :heavy_check_mark: 
  - you have paid attention to almost all of the details :heavy_check_mark: 

> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Just keep in mind that Microverse has a standard for the project requirements, to guarantee that you will be able to become a great developer, and both you and I have to follow them!

___
Cheers and Happy Coding! :heart:

> *As described in the [Code reviews limit Policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of code reviews per project (you can check the exact number in your Dashboard). If you think that the code review was not fair, you can [request a second opinion using this form](https://airtable.com/shrQAqnBwek5a0O0s).*

**Comment by zainsadaqat** [comment]
## Thank you so much @fernandorpm for approving this project

![](https://media2.giphy.com/media/fxI1G5PNC5esyNlIUs/giphy.gif)
